modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="negative_n"
version="1.3.1 Pre-Release 1"
displayName="Negative-N"
credits="The Mod made by Killar.exe and Fuzy and use MCreator"
displayURL="https://www.curseforge.com/minecraft/mc-mods/negative-n"
logoFile="logo.png"
authors="Killar.exe, Rainer"
description='''
A mod create by Killar.exe and Fuzy with new things to discover!
'''

[[dependencies.negative_n]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




