modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="negativen"
version="1.2.3 Release"
displayName="Negative-N"
credits="The Mod made by Killar.exe and Fuzy"
displayURL="https://www.curseforge.com/minecraft/mc-mods/negative-n"
logoFile="logo.png"
authors="Killar.exe, Fuzy/blackwarexe"
description='''
A mod create by Killar.exe and Fuzy with new things to discover!
'''

[[dependencies.negativen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




